### ISSUE TITLE
SubSection Numbering isn't restarted

### ISSUE THREAD

**Issue by Jerksen** [robole/vscode-marky-dynamic#1]
Hey Love the extension by the way! The issue I found is that the subsection numbering is not reset at any point. To reproduce, create a markdown document with the following structure and use the extension to add section numbering:

```markdown
# Title
## Section 1
### Section 1.1
## Section 2
### Section 2.1
```

you will get the following out:

```markdown
# Title
## 1. Section 1
### 1.1 Section 1.1
## 2. Section 2
### 2.2 Section 2.1
```

The problem being in `### 2.2 Section 2.1`

I've never done js or vscode extension dev and won't be able to try and figure it out until the weekend. 

I think there needs need some logic around https://github.com/robole/vscode-marky-dynamic/blob/5931f4293eb19d9945afc71cc5a0be444e14c744/src/document.js#L168 to detect a transition to a higher level and reset all sub-section numbers back to 0.

**Comment by robole** [comment]
hi @Jerksen 

Thanks for reporting the issue. If you want to investigate it, go for it! It sounds like adding a conditional will reset that counter.

I will try to get around to it soon.

**Comment by robole** [comment]
Issue fixed. See [PR](https://github.com/robole/vscode-marky-dynamic/pull/2).
